/*                                                                           */
/* File:       ./cdn_ram_stub_addr_map.h                                     */
/* Creator:    bemanuel                                                      */
/* Time:       Friday Nov 17, 2017 [12:25:44 am]                             */
/*                                                                           */
/* Path:       /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/work*/
/* Arguments:  /grid/scp/hw/tools/blueprint/3.7.5/Linux-64bit/blueprint -odir*/
/*             . -I                                                          */
/*             /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/*/
/*             -codegen                                                      */
/*             /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/ansicdiag.codegen*/
/*             -ansicdiag -typeprefix CDN_DEMO_TB_RAM_INTEGRATION            */
/*             /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/cdn_ram_stub_regs_map.rdl*/
/*                                                                           */
/* Sources:    /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/cdn_ram_stub_regs_map.rdl*/
/*             /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/cdn_ram_stub_regs.rdl*/
/*             /proj/giggle/work/fmalaspi/generated_cfgs_out/ip7014a/gem_gxl/func_ver/sanity/demo_tb/verif/uvc_lib/cdn_demo_ram_integration/rdl/ansicdiag.pm*/
/*                                                                           */
/* Blueprint:   3.7.5 (Thu Mar 1 22:27:42 PST 2012)                          */
/* Machine:    lvloginb                                                      */
/* OS:         Linux 2.6.32-431.11.2.el6.x86_64                              */
/* Description:                                                              */
/*                                                                           */
/* No Description Provided                                                   */
/*                                                                           */
/* Copyright (C) 2017 Denali Software Inc.  All rights reserved              */
/* THIS FILE IS AUTOMATICALLY GENERATED BY DENALI BLUEPRINT, DO NOT EDIT     */
/*                                                                           */


#ifndef __REG_CDN_RAM_STUB_ADDR_MAP_H__
#define __REG_CDN_RAM_STUB_ADDR_MAP_H__

#include "cdn_ram_stub_addr_map_macro.h"

#ifndef __REG_MASTER_APB_REGISTER_BLOCK_TYPE__
#define __REG_MASTER_APB_REGISTER_BLOCK_TYPE__

struct master_apb_register_block_type {
  volatile uint32_t MASTER_CTRL_REG;              /*        0x0 - 0x4        */
  volatile uint32_t NUM_OF_SRAM;                  /*        0x4 - 0x8        */
  volatile uint32_t NUM_OF_DP1R1W;                /*        0x8 - 0xc        */
  volatile uint32_t NUM_OF_DP2R2W;                /*        0xc - 0x10       */
  volatile uint32_t NUM_OF_RF;                    /*       0x10 - 0x14       */
  volatile uint32_t NUM_OF_SRAM_BE;               /*       0x14 - 0x18       */
  volatile uint32_t NUM_OF_DP1R1W_BE;             /*       0x18 - 0x1c       */
  volatile uint32_t NUM_OF_DP2R2W_BE;             /*       0x1c - 0x20       */
  volatile uint32_t NUM_OF_RF_BE;                 /*       0x20 - 0x24       */
};

#endif /* __REG_MASTER_APB_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_SRAM_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_SRAM_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct sram_test_function_register_block_type {
  volatile uint32_t SRAM_CTRL_REG0;               /*        0x0 - 0x4        */
  volatile uint32_t SRAM_CTRL_REG1;               /*        0x4 - 0x8        */
  volatile uint32_t SRAM_CTRL_REG2;               /*        0x8 - 0xc        */
  volatile uint32_t SRAM_CTRL_REG3;               /*        0xc - 0x10       */
  volatile uint32_t SRAM_CTRL_REG4;               /*       0x10 - 0x14       */
  volatile uint32_t SRAM_CTRL_REG5;               /*       0x14 - 0x18       */
  volatile uint32_t SRAM_CTRL_REG6;               /*       0x18 - 0x1c       */
  volatile uint32_t SRAM_CTRL_REG7;               /*       0x1c - 0x20       */
  volatile uint32_t SRAM_CTRL_REG8;               /*       0x20 - 0x24       */
  volatile uint32_t SRAM_CTRL_REG9;               /*       0x24 - 0x28       */
  volatile uint32_t SRAM_CTRL_REG10;              /*       0x28 - 0x2c       */
  volatile uint32_t SRAM_CTRL_REG11;              /*       0x2c - 0x30       */
  volatile uint32_t SRAM_CTRL_REG12;              /*       0x30 - 0x34       */
  volatile uint32_t SRAM_CTRL_REG13;              /*       0x34 - 0x38       */
  volatile uint32_t SRAM_CTRL_REG14;              /*       0x38 - 0x3c       */
  volatile uint32_t SRAM_CTRL_REG15;              /*       0x3c - 0x40       */
  volatile uint32_t SRAM_CTRL_REG16;              /*       0x40 - 0x44       */
  volatile uint32_t SRAM_CTRL_REG17;              /*       0x44 - 0x48       */
  volatile uint32_t SRAM_CTRL_REG18;              /*       0x48 - 0x4c       */
  volatile uint32_t SRAM_CTRL_REG19;              /*       0x4c - 0x50       */
  volatile uint32_t SRAM_CTRL_REG20;              /*       0x50 - 0x54       */
  volatile uint32_t SRAM_CTRL_REG21;              /*       0x54 - 0x58       */
  volatile uint32_t SRAM_CTRL_REG22;              /*       0x58 - 0x5c       */
  volatile uint32_t SRAM_CTRL_REG23;              /*       0x5c - 0x60       */
  volatile uint32_t SRAM_CTRL_REG24;              /*       0x60 - 0x64       */
  volatile uint32_t SRAM_CTRL_REG25;              /*       0x64 - 0x68       */
  volatile uint32_t SRAM_CTRL_REG26;              /*       0x68 - 0x6c       */
  volatile uint32_t SRAM_CTRL_REG27;              /*       0x6c - 0x70       */
  volatile uint32_t SRAM_CTRL_REG28;              /*       0x70 - 0x74       */
  volatile uint32_t SRAM_CTRL_REG29;              /*       0x74 - 0x78       */
  volatile uint32_t SRAM_CTRL_REG30;              /*       0x78 - 0x7c       */
  volatile uint32_t SRAM_CTRL_REG31;              /*       0x7c - 0x80       */
};

#endif /* __REG_SRAM_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_DP1R1W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_DP1R1W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct dp1r1w_test_function_register_block_type {
  volatile uint32_t DP1R1W_CTRL_REG0;             /*        0x0 - 0x4        */
  volatile uint32_t DP1R1W_CTRL_REG1;             /*        0x4 - 0x8        */
  volatile uint32_t DP1R1W_CTRL_REG2;             /*        0x8 - 0xc        */
  volatile uint32_t DP1R1W_CTRL_REG3;             /*        0xc - 0x10       */
  volatile uint32_t DP1R1W_CTRL_REG4;             /*       0x10 - 0x14       */
  volatile uint32_t DP1R1W_CTRL_REG5;             /*       0x14 - 0x18       */
  volatile uint32_t DP1R1W_CTRL_REG6;             /*       0x18 - 0x1c       */
  volatile uint32_t DP1R1W_CTRL_REG7;             /*       0x1c - 0x20       */
  volatile uint32_t DP1R1W_CTRL_REG8;             /*       0x20 - 0x24       */
  volatile uint32_t DP1R1W_CTRL_REG9;             /*       0x24 - 0x28       */
  volatile uint32_t DP1R1W_CTRL_REG10;            /*       0x28 - 0x2c       */
  volatile uint32_t DP1R1W_CTRL_REG11;            /*       0x2c - 0x30       */
  volatile uint32_t DP1R1W_CTRL_REG12;            /*       0x30 - 0x34       */
  volatile uint32_t DP1R1W_CTRL_REG13;            /*       0x34 - 0x38       */
  volatile uint32_t DP1R1W_CTRL_REG14;            /*       0x38 - 0x3c       */
  volatile uint32_t DP1R1W_CTRL_REG15;            /*       0x3c - 0x40       */
  volatile uint32_t DP1R1W_CTRL_REG16;            /*       0x40 - 0x44       */
  volatile uint32_t DP1R1W_CTRL_REG17;            /*       0x44 - 0x48       */
  volatile uint32_t DP1R1W_CTRL_REG18;            /*       0x48 - 0x4c       */
  volatile uint32_t DP1R1W_CTRL_REG19;            /*       0x4c - 0x50       */
  volatile uint32_t DP1R1W_CTRL_REG20;            /*       0x50 - 0x54       */
  volatile uint32_t DP1R1W_CTRL_REG21;            /*       0x54 - 0x58       */
  volatile uint32_t DP1R1W_CTRL_REG22;            /*       0x58 - 0x5c       */
  volatile uint32_t DP1R1W_CTRL_REG23;            /*       0x5c - 0x60       */
  volatile uint32_t DP1R1W_CTRL_REG24;            /*       0x60 - 0x64       */
  volatile uint32_t DP1R1W_CTRL_REG25;            /*       0x64 - 0x68       */
  volatile uint32_t DP1R1W_CTRL_REG26;            /*       0x68 - 0x6c       */
  volatile uint32_t DP1R1W_CTRL_REG27;            /*       0x6c - 0x70       */
  volatile uint32_t DP1R1W_CTRL_REG28;            /*       0x70 - 0x74       */
  volatile uint32_t DP1R1W_CTRL_REG29;            /*       0x74 - 0x78       */
  volatile uint32_t DP1R1W_CTRL_REG30;            /*       0x78 - 0x7c       */
  volatile uint32_t DP1R1W_CTRL_REG31;            /*       0x7c - 0x80       */
};

#endif /* __REG_DP1R1W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_DP2R2W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_DP2R2W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct dp2r2w_test_function_register_block_type {
  volatile uint32_t DP2R2W_CTRL_REG0;             /*        0x0 - 0x4        */
  volatile uint32_t DP2R2W_CTRL_REG1;             /*        0x4 - 0x8        */
  volatile uint32_t DP2R2W_CTRL_REG2;             /*        0x8 - 0xc        */
  volatile uint32_t DP2R2W_CTRL_REG3;             /*        0xc - 0x10       */
  volatile uint32_t DP2R2W_CTRL_REG4;             /*       0x10 - 0x14       */
  volatile uint32_t DP2R2W_CTRL_REG5;             /*       0x14 - 0x18       */
  volatile uint32_t DP2R2W_CTRL_REG6;             /*       0x18 - 0x1c       */
  volatile uint32_t DP2R2W_CTRL_REG7;             /*       0x1c - 0x20       */
  volatile uint32_t DP2R2W_CTRL_REG8;             /*       0x20 - 0x24       */
  volatile uint32_t DP2R2W_CTRL_REG9;             /*       0x24 - 0x28       */
  volatile uint32_t DP2R2W_CTRL_REG10;            /*       0x28 - 0x2c       */
  volatile uint32_t DP2R2W_CTRL_REG11;            /*       0x2c - 0x30       */
  volatile uint32_t DP2R2W_CTRL_REG12;            /*       0x30 - 0x34       */
  volatile uint32_t DP2R2W_CTRL_REG13;            /*       0x34 - 0x38       */
  volatile uint32_t DP2R2W_CTRL_REG14;            /*       0x38 - 0x3c       */
  volatile uint32_t DP2R2W_CTRL_REG15;            /*       0x3c - 0x40       */
  volatile uint32_t DP2R2W_CTRL_REG16;            /*       0x40 - 0x44       */
  volatile uint32_t DP2R2W_CTRL_REG17;            /*       0x44 - 0x48       */
  volatile uint32_t DP2R2W_CTRL_REG18;            /*       0x48 - 0x4c       */
  volatile uint32_t DP2R2W_CTRL_REG19;            /*       0x4c - 0x50       */
  volatile uint32_t DP2R2W_CTRL_REG20;            /*       0x50 - 0x54       */
  volatile uint32_t DP2R2W_CTRL_REG21;            /*       0x54 - 0x58       */
  volatile uint32_t DP2R2W_CTRL_REG22;            /*       0x58 - 0x5c       */
  volatile uint32_t DP2R2W_CTRL_REG23;            /*       0x5c - 0x60       */
  volatile uint32_t DP2R2W_CTRL_REG24;            /*       0x60 - 0x64       */
  volatile uint32_t DP2R2W_CTRL_REG25;            /*       0x64 - 0x68       */
  volatile uint32_t DP2R2W_CTRL_REG26;            /*       0x68 - 0x6c       */
  volatile uint32_t DP2R2W_CTRL_REG27;            /*       0x6c - 0x70       */
  volatile uint32_t DP2R2W_CTRL_REG28;            /*       0x70 - 0x74       */
  volatile uint32_t DP2R2W_CTRL_REG29;            /*       0x74 - 0x78       */
  volatile uint32_t DP2R2W_CTRL_REG30;            /*       0x78 - 0x7c       */
  volatile uint32_t DP2R2W_CTRL_REG31;            /*       0x7c - 0x80       */
};

#endif /* __REG_DP2R2W_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_RF_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_RF_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct rf_test_function_register_block_type {
  volatile uint32_t RF_CTRL_REG0;                 /*        0x0 - 0x4        */
  volatile uint32_t RF_CTRL_REG1;                 /*        0x4 - 0x8        */
  volatile uint32_t RF_CTRL_REG2;                 /*        0x8 - 0xc        */
  volatile uint32_t RF_CTRL_REG3;                 /*        0xc - 0x10       */
  volatile uint32_t RF_CTRL_REG4;                 /*       0x10 - 0x14       */
  volatile uint32_t RF_CTRL_REG5;                 /*       0x14 - 0x18       */
  volatile uint32_t RF_CTRL_REG6;                 /*       0x18 - 0x1c       */
  volatile uint32_t RF_CTRL_REG7;                 /*       0x1c - 0x20       */
  volatile uint32_t RF_CTRL_REG8;                 /*       0x20 - 0x24       */
  volatile uint32_t RF_CTRL_REG9;                 /*       0x24 - 0x28       */
  volatile uint32_t RF_CTRL_REG10;                /*       0x28 - 0x2c       */
  volatile uint32_t RF_CTRL_REG11;                /*       0x2c - 0x30       */
  volatile uint32_t RF_CTRL_REG12;                /*       0x30 - 0x34       */
  volatile uint32_t RF_CTRL_REG13;                /*       0x34 - 0x38       */
  volatile uint32_t RF_CTRL_REG14;                /*       0x38 - 0x3c       */
  volatile uint32_t RF_CTRL_REG15;                /*       0x3c - 0x40       */
  volatile uint32_t RF_CTRL_REG16;                /*       0x40 - 0x44       */
  volatile uint32_t RF_CTRL_REG17;                /*       0x44 - 0x48       */
  volatile uint32_t RF_CTRL_REG18;                /*       0x48 - 0x4c       */
  volatile uint32_t RF_CTRL_REG19;                /*       0x4c - 0x50       */
  volatile uint32_t RF_CTRL_REG20;                /*       0x50 - 0x54       */
  volatile uint32_t RF_CTRL_REG21;                /*       0x54 - 0x58       */
  volatile uint32_t RF_CTRL_REG22;                /*       0x58 - 0x5c       */
  volatile uint32_t RF_CTRL_REG23;                /*       0x5c - 0x60       */
  volatile uint32_t RF_CTRL_REG24;                /*       0x60 - 0x64       */
  volatile uint32_t RF_CTRL_REG25;                /*       0x64 - 0x68       */
  volatile uint32_t RF_CTRL_REG26;                /*       0x68 - 0x6c       */
  volatile uint32_t RF_CTRL_REG27;                /*       0x6c - 0x70       */
  volatile uint32_t RF_CTRL_REG28;                /*       0x70 - 0x74       */
  volatile uint32_t RF_CTRL_REG29;                /*       0x74 - 0x78       */
  volatile uint32_t RF_CTRL_REG30;                /*       0x78 - 0x7c       */
  volatile uint32_t RF_CTRL_REG31;                /*       0x7c - 0x80       */
};

#endif /* __REG_RF_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_SRAM_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_SRAM_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct sram_be_test_function_register_block_type {
  volatile uint32_t SRAM_BE_CTRL_REG0;            /*        0x0 - 0x4        */
  volatile uint32_t SRAM_BE_CTRL_REG1;            /*        0x4 - 0x8        */
  volatile uint32_t SRAM_BE_CTRL_REG2;            /*        0x8 - 0xc        */
  volatile uint32_t SRAM_BE_CTRL_REG3;            /*        0xc - 0x10       */
  volatile uint32_t SRAM_BE_CTRL_REG4;            /*       0x10 - 0x14       */
  volatile uint32_t SRAM_BE_CTRL_REG5;            /*       0x14 - 0x18       */
  volatile uint32_t SRAM_BE_CTRL_REG6;            /*       0x18 - 0x1c       */
  volatile uint32_t SRAM_BE_CTRL_REG7;            /*       0x1c - 0x20       */
  volatile uint32_t SRAM_BE_CTRL_REG8;            /*       0x20 - 0x24       */
  volatile uint32_t SRAM_BE_CTRL_REG9;            /*       0x24 - 0x28       */
  volatile uint32_t SRAM_BE_CTRL_REG10;           /*       0x28 - 0x2c       */
  volatile uint32_t SRAM_BE_CTRL_REG11;           /*       0x2c - 0x30       */
  volatile uint32_t SRAM_BE_CTRL_REG12;           /*       0x30 - 0x34       */
  volatile uint32_t SRAM_BE_CTRL_REG13;           /*       0x34 - 0x38       */
  volatile uint32_t SRAM_BE_CTRL_REG14;           /*       0x38 - 0x3c       */
  volatile uint32_t SRAM_BE_CTRL_REG15;           /*       0x3c - 0x40       */
  volatile uint32_t SRAM_BE_CTRL_REG16;           /*       0x40 - 0x44       */
  volatile uint32_t SRAM_BE_CTRL_REG17;           /*       0x44 - 0x48       */
  volatile uint32_t SRAM_BE_CTRL_REG18;           /*       0x48 - 0x4c       */
  volatile uint32_t SRAM_BE_CTRL_REG19;           /*       0x4c - 0x50       */
  volatile uint32_t SRAM_BE_CTRL_REG20;           /*       0x50 - 0x54       */
  volatile uint32_t SRAM_BE_CTRL_REG21;           /*       0x54 - 0x58       */
  volatile uint32_t SRAM_BE_CTRL_REG22;           /*       0x58 - 0x5c       */
  volatile uint32_t SRAM_BE_CTRL_REG23;           /*       0x5c - 0x60       */
  volatile uint32_t SRAM_BE_CTRL_REG24;           /*       0x60 - 0x64       */
  volatile uint32_t SRAM_BE_CTRL_REG25;           /*       0x64 - 0x68       */
  volatile uint32_t SRAM_BE_CTRL_REG26;           /*       0x68 - 0x6c       */
  volatile uint32_t SRAM_BE_CTRL_REG27;           /*       0x6c - 0x70       */
  volatile uint32_t SRAM_BE_CTRL_REG28;           /*       0x70 - 0x74       */
  volatile uint32_t SRAM_BE_CTRL_REG29;           /*       0x74 - 0x78       */
  volatile uint32_t SRAM_BE_CTRL_REG30;           /*       0x78 - 0x7c       */
  volatile uint32_t SRAM_BE_CTRL_REG31;           /*       0x7c - 0x80       */
};

#endif /* __REG_SRAM_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_DP1R1W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_DP1R1W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct dp1r1w_be_test_function_register_block_type {
  volatile uint32_t DP1R1W_BE_CTRL_REG0;          /*        0x0 - 0x4        */
  volatile uint32_t DP1R1W_BE_CTRL_REG1;          /*        0x4 - 0x8        */
  volatile uint32_t DP1R1W_BE_CTRL_REG2;          /*        0x8 - 0xc        */
  volatile uint32_t DP1R1W_BE_CTRL_REG3;          /*        0xc - 0x10       */
  volatile uint32_t DP1R1W_BE_CTRL_REG4;          /*       0x10 - 0x14       */
  volatile uint32_t DP1R1W_BE_CTRL_REG5;          /*       0x14 - 0x18       */
  volatile uint32_t DP1R1W_BE_CTRL_REG6;          /*       0x18 - 0x1c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG7;          /*       0x1c - 0x20       */
  volatile uint32_t DP1R1W_BE_CTRL_REG8;          /*       0x20 - 0x24       */
  volatile uint32_t DP1R1W_BE_CTRL_REG9;          /*       0x24 - 0x28       */
  volatile uint32_t DP1R1W_BE_CTRL_REG10;         /*       0x28 - 0x2c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG11;         /*       0x2c - 0x30       */
  volatile uint32_t DP1R1W_BE_CTRL_REG12;         /*       0x30 - 0x34       */
  volatile uint32_t DP1R1W_BE_CTRL_REG13;         /*       0x34 - 0x38       */
  volatile uint32_t DP1R1W_BE_CTRL_REG14;         /*       0x38 - 0x3c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG15;         /*       0x3c - 0x40       */
  volatile uint32_t DP1R1W_BE_CTRL_REG16;         /*       0x40 - 0x44       */
  volatile uint32_t DP1R1W_BE_CTRL_REG17;         /*       0x44 - 0x48       */
  volatile uint32_t DP1R1W_BE_CTRL_REG18;         /*       0x48 - 0x4c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG19;         /*       0x4c - 0x50       */
  volatile uint32_t DP1R1W_BE_CTRL_REG20;         /*       0x50 - 0x54       */
  volatile uint32_t DP1R1W_BE_CTRL_REG21;         /*       0x54 - 0x58       */
  volatile uint32_t DP1R1W_BE_CTRL_REG22;         /*       0x58 - 0x5c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG23;         /*       0x5c - 0x60       */
  volatile uint32_t DP1R1W_BE_CTRL_REG24;         /*       0x60 - 0x64       */
  volatile uint32_t DP1R1W_BE_CTRL_REG25;         /*       0x64 - 0x68       */
  volatile uint32_t DP1R1W_BE_CTRL_REG26;         /*       0x68 - 0x6c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG27;         /*       0x6c - 0x70       */
  volatile uint32_t DP1R1W_BE_CTRL_REG28;         /*       0x70 - 0x74       */
  volatile uint32_t DP1R1W_BE_CTRL_REG29;         /*       0x74 - 0x78       */
  volatile uint32_t DP1R1W_BE_CTRL_REG30;         /*       0x78 - 0x7c       */
  volatile uint32_t DP1R1W_BE_CTRL_REG31;         /*       0x7c - 0x80       */
};

#endif /* __REG_DP1R1W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_DP2R2W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_DP2R2W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct dp2r2w_be_test_function_register_block_type {
  volatile uint32_t DP2R2W_BE_CTRL_REG0;          /*        0x0 - 0x4        */
  volatile uint32_t DP2R2W_BE_CTRL_REG1;          /*        0x4 - 0x8        */
  volatile uint32_t DP2R2W_BE_CTRL_REG2;          /*        0x8 - 0xc        */
  volatile uint32_t DP2R2W_BE_CTRL_REG3;          /*        0xc - 0x10       */
  volatile uint32_t DP2R2W_BE_CTRL_REG4;          /*       0x10 - 0x14       */
  volatile uint32_t DP2R2W_BE_CTRL_REG5;          /*       0x14 - 0x18       */
  volatile uint32_t DP2R2W_BE_CTRL_REG6;          /*       0x18 - 0x1c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG7;          /*       0x1c - 0x20       */
  volatile uint32_t DP2R2W_BE_CTRL_REG8;          /*       0x20 - 0x24       */
  volatile uint32_t DP2R2W_BE_CTRL_REG9;          /*       0x24 - 0x28       */
  volatile uint32_t DP2R2W_BE_CTRL_REG10;         /*       0x28 - 0x2c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG11;         /*       0x2c - 0x30       */
  volatile uint32_t DP2R2W_BE_CTRL_REG12;         /*       0x30 - 0x34       */
  volatile uint32_t DP2R2W_BE_CTRL_REG13;         /*       0x34 - 0x38       */
  volatile uint32_t DP2R2W_BE_CTRL_REG14;         /*       0x38 - 0x3c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG15;         /*       0x3c - 0x40       */
  volatile uint32_t DP2R2W_BE_CTRL_REG16;         /*       0x40 - 0x44       */
  volatile uint32_t DP2R2W_BE_CTRL_REG17;         /*       0x44 - 0x48       */
  volatile uint32_t DP2R2W_BE_CTRL_REG18;         /*       0x48 - 0x4c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG19;         /*       0x4c - 0x50       */
  volatile uint32_t DP2R2W_BE_CTRL_REG20;         /*       0x50 - 0x54       */
  volatile uint32_t DP2R2W_BE_CTRL_REG21;         /*       0x54 - 0x58       */
  volatile uint32_t DP2R2W_BE_CTRL_REG22;         /*       0x58 - 0x5c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG23;         /*       0x5c - 0x60       */
  volatile uint32_t DP2R2W_BE_CTRL_REG24;         /*       0x60 - 0x64       */
  volatile uint32_t DP2R2W_BE_CTRL_REG25;         /*       0x64 - 0x68       */
  volatile uint32_t DP2R2W_BE_CTRL_REG26;         /*       0x68 - 0x6c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG27;         /*       0x6c - 0x70       */
  volatile uint32_t DP2R2W_BE_CTRL_REG28;         /*       0x70 - 0x74       */
  volatile uint32_t DP2R2W_BE_CTRL_REG29;         /*       0x74 - 0x78       */
  volatile uint32_t DP2R2W_BE_CTRL_REG30;         /*       0x78 - 0x7c       */
  volatile uint32_t DP2R2W_BE_CTRL_REG31;         /*       0x7c - 0x80       */
};

#endif /* __REG_DP2R2W_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_RF_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__
#define __REG_RF_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__

struct rf_be_test_function_register_block_type {
  volatile uint32_t RF_BE_CTRL_REG0;              /*        0x0 - 0x4        */
  volatile uint32_t RF_BE_CTRL_REG1;              /*        0x4 - 0x8        */
  volatile uint32_t RF_BE_CTRL_REG2;              /*        0x8 - 0xc        */
  volatile uint32_t RF_BE_CTRL_REG3;              /*        0xc - 0x10       */
  volatile uint32_t RF_BE_CTRL_REG4;              /*       0x10 - 0x14       */
  volatile uint32_t RF_BE_CTRL_REG5;              /*       0x14 - 0x18       */
  volatile uint32_t RF_BE_CTRL_REG6;              /*       0x18 - 0x1c       */
  volatile uint32_t RF_BE_CTRL_REG7;              /*       0x1c - 0x20       */
  volatile uint32_t RF_BE_CTRL_REG8;              /*       0x20 - 0x24       */
  volatile uint32_t RF_BE_CTRL_REG9;              /*       0x24 - 0x28       */
  volatile uint32_t RF_BE_CTRL_REG10;             /*       0x28 - 0x2c       */
  volatile uint32_t RF_BE_CTRL_REG11;             /*       0x2c - 0x30       */
  volatile uint32_t RF_BE_CTRL_REG12;             /*       0x30 - 0x34       */
  volatile uint32_t RF_BE_CTRL_REG13;             /*       0x34 - 0x38       */
  volatile uint32_t RF_BE_CTRL_REG14;             /*       0x38 - 0x3c       */
  volatile uint32_t RF_BE_CTRL_REG15;             /*       0x3c - 0x40       */
  volatile uint32_t RF_BE_CTRL_REG16;             /*       0x40 - 0x44       */
  volatile uint32_t RF_BE_CTRL_REG17;             /*       0x44 - 0x48       */
  volatile uint32_t RF_BE_CTRL_REG18;             /*       0x48 - 0x4c       */
  volatile uint32_t RF_BE_CTRL_REG19;             /*       0x4c - 0x50       */
  volatile uint32_t RF_BE_CTRL_REG20;             /*       0x50 - 0x54       */
  volatile uint32_t RF_BE_CTRL_REG21;             /*       0x54 - 0x58       */
  volatile uint32_t RF_BE_CTRL_REG22;             /*       0x58 - 0x5c       */
  volatile uint32_t RF_BE_CTRL_REG23;             /*       0x5c - 0x60       */
  volatile uint32_t RF_BE_CTRL_REG24;             /*       0x60 - 0x64       */
  volatile uint32_t RF_BE_CTRL_REG25;             /*       0x64 - 0x68       */
  volatile uint32_t RF_BE_CTRL_REG26;             /*       0x68 - 0x6c       */
  volatile uint32_t RF_BE_CTRL_REG27;             /*       0x6c - 0x70       */
  volatile uint32_t RF_BE_CTRL_REG28;             /*       0x70 - 0x74       */
  volatile uint32_t RF_BE_CTRL_REG29;             /*       0x74 - 0x78       */
  volatile uint32_t RF_BE_CTRL_REG30;             /*       0x78 - 0x7c       */
  volatile uint32_t RF_BE_CTRL_REG31;             /*       0x7c - 0x80       */
};

#endif /* __REG_RF_BE_TEST_FUNCTION_REGISTER_BLOCK_TYPE__ */

#ifndef __REG_CDN_RAM_STUB_ADDR_MAP__
#define __REG_CDN_RAM_STUB_ADDR_MAP__

struct cdn_ram_stub_addr_map {
  struct master_apb_register_block_type master_apb_reg_block;
                                                  /*        0x0 - 0x24       */
  volatile char pad__0[0xdc];                     /*       0x24 - 0x100      */
  struct sram_test_function_register_block_type sram_test_func_reg_block;
                                                  /*      0x100 - 0x180      */
  volatile char pad__1[0x80];                     /*      0x180 - 0x200      */
  struct dp1r1w_test_function_register_block_type dp1r1w_test_func_reg_block;
                                                  /*      0x200 - 0x280      */
  volatile char pad__2[0x80];                     /*      0x280 - 0x300      */
  struct dp2r2w_test_function_register_block_type dp2r2w_test_func_reg_block;
                                                  /*      0x300 - 0x380      */
  volatile char pad__3[0x80];                     /*      0x380 - 0x400      */
  struct rf_test_function_register_block_type rf_test_func_reg_block;
                                                  /*      0x400 - 0x480      */
  volatile char pad__4[0x80];                     /*      0x480 - 0x500      */
  struct sram_be_test_function_register_block_type sram_be_test_func_reg_block;
                                                  /*      0x500 - 0x580      */
  volatile char pad__5[0x80];                     /*      0x580 - 0x600      */
  struct dp1r1w_be_test_function_register_block_type dp1r1w_be_test_func_reg_block;
                                                  /*      0x600 - 0x680      */
  volatile char pad__6[0x80];                     /*      0x680 - 0x700      */
  struct dp2r2w_be_test_function_register_block_type dp2r2w_be_test_func_reg_block;
                                                  /*      0x700 - 0x780      */
  volatile char pad__7[0x80];                     /*      0x780 - 0x800      */
  struct rf_be_test_function_register_block_type rf_be_test_func_reg_block;
                                                  /*      0x800 - 0x880      */
};

#endif /* __REG_CDN_RAM_STUB_ADDR_MAP__ */

#endif /* __REG_CDN_RAM_STUB_ADDR_MAP_H__ */
