
vpxmode

// Design Rule Waivers for environment issues

add rule filter hdl_default_checks/directive_checks/DIR6.1/1  -message  "* timescale" -description "timescale directive warning"  -rule  hdl_default_checks/directive_checks/DIR6.1
add rule filter hdl_default_checks/directive_checks/DIR6.2/1a  -message  "*: `ifdef" -description "Sync flop define control for code generation"  -rule  hdl_default_checks/directive_checks/DIR6.2
add rule filter hdl_default_checks/directive_checks/DIR6.2/1b  -message  "*: `ifndef" -description "Sync flop define control for code generation"  -rule  hdl_default_checks/directive_checks/DIR6.2
add rule filter hdl_default_checks/directive_checks/DIR6.2/1c  -message  "*: `endif" -description "Sync flop define control for code generation"  -rule  hdl_default_checks/directive_checks/DIR6.2
add rule filter hdl_default_checks/directive_checks/DIR6.2/1d  -message  "*: `else" -description "Sync flop define control for code generation"  -rule  hdl_default_checks/directive_checks/DIR6.2
add rule filter hdl_default_checks/ignored_checks/IGN3.2/1  -message  "*/process/tsmc/TSMC28HPM/*" -rule  hdl_default_checks/ignored_checks/IGN3.2 
add rule filter hdl_default_checks/verilog_checks/VLG9.2/1 -description "defines expected in configurable code" -message  "*' Text macro '*' is defined"  -rule  hdl_default_checks/verilog_checks/VLG9.2 
add rule filter hdl_default_checks/hierarchy_checks/HRC1.4/1  -message  "*" -description "Unused tech cells in TSMC lib"  -rule  hdl_default_checks/hierarchy_checks/HRC1.4 

//To be fixed missing default assignment in if priority clause
add rule filter hdl_default_checks/rtl_checks/RTL1.2/1  -message  "In line 131, file '*/csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34): packet_grant_r" -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/2  -message  "In line 136, file '*/csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34): arb_locked" -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/3  -message  "In line 1501, file '*/csi2tx_data_packer.v' (csi2tx_data_packer_WC_WIDTH16_PIXEL_DATA_WIDTH32_DATA_TYPE_WIDTH6): line_active"  -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/4  -message  "In line 1471, file '*/csi2tx_data_packer.v' (csi2tx_data_packer_WC_WIDTH16_PIXEL_DATA_WIDTH32_DATA_TYPE_WIDTH6): data_out"  -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/5  -message  "In line 1472, file '*/csi2tx_data_packer.v' (csi2tx_data_packer_WC_WIDTH16_PIXEL_DATA_WIDTH32_DATA_TYPE_WIDTH6): data_out_valid"  -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/6  -message  "In line 1504, file '*/csi2tx_data_packer.v' (csi2tx_data_packer_WC_WIDTH16_PIXEL_DATA_WIDTH32_DATA_TYPE_WIDTH6): flush_crc"  -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/7  -message  "In line 621, file '*/csi2tx_ln_ctrl.v' (*): in_a_line"  -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/11 -description " start and end are mutally exclusive" -message  "In line 613, file '*/mipi_csi2tx_isp/rtl/./csi2tx_ln_ctrl.v' (csi2tx_ln_ctrl_NUM_STREAMS2_TX_DATA_HS_WIDTH8_PACKET_WIDTH34_REG_WAIT_BURST_TIME_WIDTH32): in_a_line" -rule  hdl_default_checks/rtl_checks/RTL1.2 


// default at start of process
add rule filter hdl_default_checks/rtl_checks/RTL1.2/1e -description "Default statement is the first statement in the process.  This coding style is allowed." -message  "In line *, file '*/mipi_csi2tx_isp/rtl/./csi2tx_async_fifo.v' (*): valid_b_r" -rule  hdl_default_checks/rtl_checks/RTL1.2 
add rule filter hdl_default_checks/rtl_checks/RTL1.2/7a  -message  "In line 1481, file '*/csi2tx_data_packer.v' (csi2tx_data_packer_WC_WIDTH16_PIXEL_DATA_WIDTH32_DATA_TYPE_WIDTH6): crc_extra"  -rule  hdl_default_checks/rtl_checks/RTL1.2 

//To be fixed with clock gating
add Rule Filter hdl_default_checks/hierarchy_checks/HRC3.16/1  -rule hdl_default_checks/hierarchy_checks/HRC3.16 -description 'Unused wires leftover due to clock gate control removal'  -message "*"
add rule filter hdl_default_checks/rtl_checks/RTL14/1  -message  "In line 1158, file '*/csi2tx_toplevel.v' (csi2tx_toplevel): Floating signal pclk_req in module csi2tx_toplevel is detected" -description 'Unused wires leftover due to clock gate control removal' -rule  hdl_default_checks/rtl_checks/RTL14

//add rule filter hdl_default_checks/hierarchy_checks/HRC3.5b/1  -message  "*On instance GEN_STREAMS[0].u_protocol: pixel_clk_req" -description 'Unused wires leftover due to clock gate control removal'  -rule  hdl_default_checks/hierarchy_checks/HRC3.5b
//add rule filter hdl_default_checks/hierarchy_checks/HRC3.5b/2  -message  "*On instance GEN_STREAMS[1].u_protocol: pixel_clk_req" -description 'Unused wires leftover due to clock gate control removal'  -rule  hdl_default_checks/hierarchy_checks/HRC3.5b

add rule filter hdl_default_checks/hierarchy_checks/HRC3.5b/1  -message  "In line 774, file '/projects/kessel_nosnap/work/sproul/mipi_csi2tx_isp//rtl/./csi2tx_toplevel.v' (csi2tx_toplevel): On instance GEN_STREAMS[0].u_protocol: pixel_clk_req" -exact  -rule  hdl_default_checks/hierarchy_checks/HRC3.5b
add rule filter hdl_default_checks/hierarchy_checks/HRC3.5b/2  -message  "In line 774, file '/projects/kessel_nosnap/work/sproul/mipi_csi2tx_isp//rtl/./csi2tx_toplevel.v' (csi2tx_toplevel): On instance GEN_STREAMS[1].u_protocol: pixel_clk_req" -exact  -rule  hdl_default_checks/hierarchy_checks/HRC3.5b

// Design Rule Waivers for Integer arithmetic in counters, comparisons and generate loops
add rule filter hdl_default_checks/rtl_checks/RTL1.2/8  -message  "In line 990, file '*/csi2tx_ctrl_reg.v' (csi2tx_ctrl_reg*): err_event_r" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL1.2

add rule filter hdl_default_checks/rtl_checks/RTL1.5b/1   -message  "In line 152, file '*/csi2tx_packet_ctrl.v' *vc_frame_counters_r*" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/1a  -message  "In line 152, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): vc_frame_counters_r[0] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b 
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/1b  -message  "In line 152, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): vc_frame_counters_r[1] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b 
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/1c  -message  "In line 152, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): vc_frame_counters_r[2] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b 
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/1d  -message  "In line 152, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): vc_frame_counters_r[3] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b 

add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2   -message  "In line 187, file '*/csi2tx_packet_ctrl.v' *dt_line_counters_r*" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2a  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[0] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b 
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2b  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[1] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2c  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[2] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2d  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[3] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2e  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[4] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2f  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[5] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2g  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[6] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2h  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[7] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2i  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[8] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b
add rule filter hdl_default_checks/rtl_checks/RTL1.5b/2j  -message  "In line 187, file '*/csi2tx_packet_ctrl.v' (csi2tx_packet_ctrl_VC_WIDTH2_DT_WIDTH3_WC_WIDTH16_DATA_TYPE_WIDTH6_DT_NUMBER8_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_VC_NUMBER4_PIXEL_DATA_WIDTH32): dt_line_counters_r[9] LHS:16 RHS:17" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b

add rule filter hdl_default_checks/rtl_checks/RTL1.5b/3   -message  "*/csi2tx_packet_ctrl.v*byte_cnt_nxt*" -description "arithmetic operations will not exceed in normal operation" -rule  hdl_default_checks/rtl_checks/RTL1.5b

add rule filter hdl_default_checks/rtl_checks/RTL1.9/1   -message  "In line 110, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/2   -message  "In line 113, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/3   -message  "In line 116, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/4   -message  "In line 119, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/5   -message  "In line 126, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/6   -message  "In line 128, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/7   -message  "In line 129, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/8   -message  "In line 135, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/9   -message  "In line 137, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/10  -message  "In line 138, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/11  -message  "In line 144, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/12  -message  "In line 153, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/13  -message  "In line 155, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/14  -message  "In line 156, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/15  -message  "In line 162, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/16  -message  "In line 164, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/17  -message  "In line 165, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/18  -message  "In line 171, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/19  -message  "In line 173, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/20  -message  "In line 174, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/21  -message  "In line 180, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/22  -message  "In line 182, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/23  -message  "In line 183, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/24  -message  "In line 189, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/25  -message  "In line 191, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/26  -message  "In line 192, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:16 RHS:32" -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/27  -message  "In line 196, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/28  -message  "In line 197, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/29  -message  "In line 198, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/30  -message  "In line 199, file '*/csi2tx_reg_constants.v' (csi2tx_ctrl_reg*): LHS:6 RHS:32"  -description "no value used for bit-width in default assignment"  -rule  hdl_default_checks/rtl_checks/RTL1.9 

add rule filter hdl_default_checks/rtl_checks/RTL1.9/31  -message  "In line 78, file '*/csi2tx_async_fifo.v' (csi2tx_async_fifo_DA_WIDTH34_AD_WIDTH6_DEPTH64_FL_WIDTH6): LHS:14 RHS:32"  -rule  hdl_default_checks/rtl_checks/RTL1.9 
add rule filter hdl_default_checks/rtl_checks/RTL1.9/32  -message  "In line 79, file '*/csi2tx_async_fifo.v' (csi2tx_async_fifo_DA_WIDTH34_AD_WIDTH6_DEPTH64_FL_WIDTH6): LHS:7 RHS:32"  -rule  hdl_default_checks/rtl_checks/RTL1.9 


add rule filter hdl_default_checks/rtl_checks/RTL7.10/1  -message  "In line 69, file '*/csi2tx_generic_fifo_ram.v' (csi2tx_generic_fifo_ram)" -description "Comparison between for loop index and variable" -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/2  -message  "In line 62, file '*/cdn_syncflop.v' (cdn_syncflop_RESET_STATE0_NUM_FLOPS2_DIN_W1_ENABLE_RANDOMIZATION*)" -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/3  -message  "In line 62, file '*/cdn_syncflop.v' (cdn_syncflop_RESET_STATE1_NUM_FLOPS2_DIN_W1_ENABLE_RANDOMIZATION*)" -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4  -message  "In line 479, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4b  -message  "In line 489, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4c  -message  "In line 505, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4d  -message  "In line 549, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4e  -message  "In line 660, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4f  -message  "In line 724, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4g  -message  "In line 763, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4h  -message  "In line 818, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4i  -message  "In line 948, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4j  -message  "In line 982, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4k  -message  "In line 1005, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4l  -message  "In line 1136, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4m  -message  "In line 1164, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4n  -message  "In line 1197, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4o  -message  "In line 1236, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4op -message  "In line 1226, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/4p  -message  "In line 1272, file '*/csi2tx_ctrl_reg.v' (*)" -description "Comparison of integer in counter loop compared with configuration parameter"  -rule  hdl_default_checks/rtl_checks/RTL7.10 

add rule filter hdl_default_checks/rtl_checks/RTL7.10/5  -message  "In line 757, file '*/csi2tx_toplevel.v' (csi2tx_toplevel)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/6  -message  "In line 402, file '*/csi2tx_protocol.v' (csi2tx_protocol_SYNC_APB_PIXEL0_PIXEL_DATA_WIDTH32_PACKET_WIDTH34_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_WC_WIDTH16_DATA_TYPE_WIDTH6_VC_WIDTH2_DT_WIDTH3_VC_NUMBER4_DT_NUMBER8_ASYNC_FIFO_AD_WIDTH6_ASYNC_FIFO_DEPTH64_ASYNC_FIFO_FL_WIDTH6)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/7  -message  "In line 395, file '*/csi2tx_protocol.v' (csi2tx_protocol_SYNC_APB_PIXEL0_PIXEL_DATA_WIDTH32_PACKET_WIDTH34_VC_MAX_FRAME_NUMBER_WIDTH16_DT_MAX_LINE_NUMBER_WIDTH16_WC_WIDTH16_DATA_TYPE_WIDTH6_VC_WIDTH2_DT_WIDTH3_VC_NUMBER4_DT_NUMBER8_ASYNC_FIFO_AD_WIDTH6_ASYNC_FIFO_DEPTH64_ASYNC_FIFO_FL_WIDTH6)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/8  -message  "In line 78, file '*/csi2tx_async_fifo.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/9  -message  "In line 127, file '*/csi2tx_packet_ctrl.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/10  -message  "In line 164, file '*/csi2tx_packet_ctrl.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/11  -message  "In line 169, file '*/csi2tx_packet_ctrl.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/12  -message  "In line 220, file '*/csi2tx_packet_ctrl.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/13  -message  "In line 229, file '*/csi2tx_packet_ctrl.v' (*)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/14  -message  "In line 133, file '*/csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/15  -message  "In line 143, file '*/csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34)" -description "Comparison between for loop index and variable"  -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/16  -message  "In line 392, file '*/csi2tx_ln_ctrl.v' (*)" -description "Comparison checking with integer for number of steams"  -rule  hdl_default_checks/rtl_checks/RTL7.10
add rule filter hdl_default_checks/rtl_checks/RTL7.10/25  -message  "In line 481, file '/projects/kessel/work/mlewis/mipi_csi2tx_isp/rtl/./csi2tx_async_fifo.v' (csi2tx_async_fifo_DA_WIDTH34_AD_WIDTH6_DEPTH64_FL_WIDTH6)" -description "Comparison between 2 32 bit decimal values so not an issue." -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/26  -message  "In line 485, file '/projects/kessel/work/mlewis/mipi_csi2tx_isp/rtl/./csi2tx_async_fifo.v' (csi2tx_async_fifo_DA_WIDTH34_AD_WIDTH6_DEPTH64_FL_WIDTH6)" -description "Comparison between 2 32 bit decimal values so not an issue."  -rule  hdl_default_checks/rtl_checks/RTL7.10 


add rule filter hdl_default_checks/rtl_checks/RTL7.10/21 -description "Comparison checking with integer for number of steams" -message  "In line 174, file '*/mipi_csi2tx_isp/rtl/./csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34)"   -rule  hdl_default_checks/rtl_checks/RTL7.10 
add rule filter hdl_default_checks/rtl_checks/RTL7.10/22 -description "Comparison checking with integer for number of steams" -message  "In line 184, file '*/mipi_csi2tx_isp/rtl/./csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb_NUM_STREAMS2_PACKET_WIDTH34)"   -rule  hdl_default_checks/rtl_checks/RTL7.10 



add rule filter hdl_default_checks/rtl_checks/RTL7.10a/1  -message  "In line 142, file '*/csi2tx_packet_ctrl.v' (*): sizes are 2-bit at col 38 vs. 32-bit at col 57" -description "Comparison between for loop index and variable" -rule  hdl_default_checks/rtl_checks/RTL7.10a 
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/2  -message  "In line 180, file '*/csi2tx_packet_ctrl.v' (*): sizes are 3-bit at col 38 vs. 32-bit at col 54" -description "Comparison between for loop index and variable" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/7  -message  "In line 196, file '*/csi2tx_packet_ctrl.v' (*): sizes are 3-bit at col 39 vs. 32-bit at col 55" -description "Comparison between for loop index and variable" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/8  -message  "In line 229, file '*/csi2tx_packet_ctrl.v' (*): sizes are 3-bit at col 74 vs. 32-bit at col 90" -description "Comparison between for loop index and variable" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/10  -message  "In line 481, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 15 vs. 32-bit at col 50" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/11  -message  "In line 491, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 15 vs. 32-bit at col 50" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/12  -message  "In line 507, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 15 vs. 32-bit at col 50" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a 
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/13  -message  "In line 552, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 19 vs. 32-bit at col 62" -description "Comparison between for loop index and register static address"  -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/14  -message  "In line 1176, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 24 vs. 32-bit at col 58" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/15  -message  "In line 1146, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 24 vs. 32-bit at col 58" -description "Comparison between for loop index and register static address"  -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/16  -message  "In line 1208, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 24 vs. 32-bit at col 60" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a
add rule filter hdl_default_checks/rtl_checks/RTL7.10a/17  -message  "In line 1235, file '*/csi2tx_ctrl_reg.v' (*): sizes are 12-bit at col 24 vs. 32-bit at col 58" -description "Comparison between for loop index and register static address" -rule  hdl_default_checks/rtl_checks/RTL7.10a

add rule filter hdl_default_checks/rtl_checks/RTL7.11/1  -message  "In line 397, file '*/csi2tx_protocol.v' (RIP_VC_BUS)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11
add rule filter hdl_default_checks/rtl_checks/RTL7.11/2  -message  "In line 404, file '*/csi2tx_protocol.v' (RIP_DT_BUS)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11
add rule filter hdl_default_checks/rtl_checks/RTL7.11/3  -message  "In line 406, file '*/csi2tx_protocol.v' (RIP_DT_BUS)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11
add rule filter hdl_default_checks/rtl_checks/RTL7.11/4  -message  "In line 408, file '*/csi2tx_protocol.v' (RIP_DT_BUS)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11
add rule filter hdl_default_checks/rtl_checks/RTL7.11/9  -message  "In line 1143, file '*/csi2tx_ctrl_reg.v' (ALL_VC_CFG_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/11  -message  "In line 1152, file '*/csi2tx_ctrl_reg.v' (ALL_VC_CFG_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/13  -message  "In line 1173, file '*/csi2tx_ctrl_reg.v' (ALL_DT_CFG_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/15  -message  "In line 1184, file '*/csi2tx_ctrl_reg.v' (ALL_DT_REG_GEN)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/17  -message  "In line 1203, file '*/csi2tx_ctrl_reg.v' (ALL_DT_FMT_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/19  -message  "In line 1205, file '*/csi2tx_ctrl_reg.v' (ALL_DT_FMT_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/21  -message  "In line 1214, file '*/csi2tx_ctrl_reg.v' (VC_REG_GEN)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/23  -message  "In line 1216, file '*/csi2tx_ctrl_reg.v' (VC_REG_GEN)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/25  -message  "In line 1232, file '*/csi2tx_ctrl_reg.v' (ALL_FL_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/27  -message  "In line 1249, file '*/csi2tx_ctrl_reg.v' (ALL_FL_REG_PROC)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 
add rule filter hdl_default_checks/rtl_checks/RTL7.11/29  -message  "In line 175, file '*/csi2tx_ln_ctrl_arb.v' (csi2tx_ln_ctrl_arb)" -description "bit vector Index calculation using parameter and loop variable" -rule  hdl_default_checks/rtl_checks/RTL7.11 

add rule filter hdl_default_checks/rtl_checks/RTL9.17/1  -message  "In line *, file '/process/tsmc/TSMC28HPM/TSMCHOME/*' (*): All outputs of * are undriven"  -rule  hdl_default_checks/rtl_checks/RTL9.17

add rule filter hdl_default_checks/rtl_checks/RTL1.2/3a  -description "The first statement is soley to catch an error condition.  If no error occurs then normal operation will take effect with the next statement. " -message  "In line *, file '*/rtl/./csi2tx_async_fifo.v' (*): popda_fsm_r"  -rule  hdl_default_checks/rtl_checks/RTL1.2 

