// Generated by Cadence Encounter(R) RTL Compiler RC14.10 - v14.10-p008_1
tclmode

# Read project.tcl from current directory if it exists, otherwise look for it in $DUT_PATH
  if [file exists "./project.tcl"] {
     puts "Sourcing ./project.tcl ..."
     source ./project.tcl
  } else {
     puts "ERROR: Can't find project.tcl in current working directory."
     exit
  }


if {$HTML_REPORT} {
setenv INFRA ${IPF_DESIGN_FLOW_SCRIPTS}/lec/app_ftp/utils
ncdecrypt ${IPF_DESIGN_FLOW_SCRIPTS}/lec/app_ftp/utils/applet.etf

$::ns(applet)::set_attr applet_server ${IPF_DESIGN_FLOW_SCRIPTS}/lec/app_ftp/server /
$::ns(applet)::set_attr applet_search_path ${IPF_DESIGN_FLOW_SCRIPTS}/lec/app_ftp/server /

applet avail

# This source has to happen here. If done earlier it causes issues
rename source _source
proc source {args} { set dir [file dirname $args]; eval ncdecrypt ${args} }

# example loading the measure applet which in turn loads the time_info applet as a dependency
applet load measure
}

vpxmode
