#------------------------------------------------------------------------------
#                                     
#            CADENCE                    Copyright (c) 2002-2014
#                                       Cadence Design Systems, Inc.
#                                       All rights reserved.
#
#  This work may not be copied, modified, re-published, uploaded, executed, or
#  distributed in any way, in any medium, whether in whole or in part, without
#  prior written permission from Cadence Design Systems, Inc.
#------------------------------------------------------------------------------
#
#    Primary Unit Name :      project.tcl
#
#          Description :      Configuration file for IPF Design Flow scripts,
#                             sourced by tool-specific scripts
#
#      Original Author :      Patrick McKeever
#
#------------------------------------------------------------------------------

## Extract the environment form the setup_project.csh
  source $env(IPF_DESIGN_FLOW_SCRIPTS)/setup/set_tcl_vars.tcl

## Setup the input and output directory variables
  source $env(IPF_DESIGN_FLOW_SCRIPTS)/setup/setup_dirs.tcl

##############################################################################
## Global variables and attributes
##############################################################################

## Modus clock constraint file for at-speed ATPG (auto-generated by flow)

  set ATPG_CLOCK_CONSTRAINTS_FILE "${CFG_DIR}/${CONFIG}/dft/constraints/clock_constraints_${CONFIG}.txt"

## Constraints file for at-speed ATPG, comment out if not required.
## Should be manually created, based on path exceptions from functional constraints.
## This file should contain path exceptions for any paths that do not meet the 
## at-speed clock timing requirements.
## These paths would typically either be false paths (known hold violations, 
## or unconstrained setup paths) or multicycle paths (where a path has been 
## constrained against a multiple of the test clock period).
## Modus uses the path exception information to create dynamic test patterns 
## that will run at the at-speed frequencies provided to the tool via the 
## flow-generated ATPG_CLOCK_CONSTRAINTS_FILE.
  
  #    set ATPG_SDC_FILE "$DUT_PATH/dft/constraints/${DESIGN}_${CONFIG}.scan.sdc"

##############################################################################
## Synthesis Effort settings
##############################################################################

    set SYN_EFF medium

##############################################################################
## Power Analysis - Activity Files and Power states
##############################################################################

## RTL Power Analysis
## If an average toggle file is available from RTL sims then please use it in
## synthesis for better power reporting. If a toggle file is not available 
## then don't specify the variables or leave them blank.  
  #   set RTL_TOGGLE_FILE ${DUT_PATH}/synth/tcf/${DESIGN}_${CONFIG}.<test_name>.tcf
  
  
## Post GLS Power Analysis    
## Select the power states to be analysed by rc_power.tcl
## Place all tcf/saif files relevant to that power state within a directory named
## after that state. The global env RTL_TOGGLE_FILE_DIR/NL_TOGGLE_FILE_DIR 
## are defined in setup_project.csh
#eg. ${RTL_TOGGLE_FILE_DIR}/*${power_state}*/*.tcf

      set POWER_STATES {p1}
 

## NL_FOR_POWER_ANALYSIS should be set to the name of the netlist that has been
## simulated in order to generate one or more toggle files, to support gate-
## level power analysis using the rc_power.tcl script.
## Use post PNR netlist

  set NL_FOR_POWER_ANALYSIS ${_PNR_DATA_PATH}/$DESIGN.postccoptincr.v

## VCD File
## If using a vcd file instead of a tcf/saif file then use these settings.
  #  set VCD_FILE <path>

## Only 1 of the following can be selected:  
  #  set VCD_TIMESTAMPS {0ns:2500000ns 3000000ns:5000000ns 6000000ns:9000000ns}
  #  set FRAME_COUNT 10

## Activity top level
## The SAIF/tcf/vcd file will include a path to the instantiated dut. When 
## running power analysis RC has to be told what the top-level of the design
## is within the activity file:
## i.e.  he dumpsaif file had a "-scope i_gem". 
## This means that the path to the top-level dut is i_gem.

      set ACTIVITY_DUT i_$DESIGN
      set SAIF_DUT i_$DESIGN
      
################################################################################
## Define Library Information
################################################################################

## Force Use of particular cells
  #    set FORCE_USE ""

## Setup the Technology library pointers.
    source  $IPF_DESIGN_FLOW_SCRIPTS/tech_lib_setup.tcl

## Select the VT library to use for optimisation
## If commented out tool will use all libraries as default
## Choices are LOW or MID
#    set LEAKAGE_LIB LOW

################################################################################
## Additonal Lib files and Handling Hard Macros / Analog blocks etc
################################################################################

## NOTE: A file with a list of libraries (./liblist.lib and ./liblist.f) to be
## read in by CDC, Spyglass and potentially other tools is produced by the 
## when executing the scripts to run those tools.
## If these files exist they will not be re-generated!

## Note if other libraries are needed, such as RAM libraries or HARD MACROS 
## following variables should be appended to include this information 
## Appending the tsmc variable convention will mean that the base scripts pick up
## the correct libraries without having to modify the scripts. - i.e.
  
  #  lappend LIBLEF "/process/tsmc/TSMC28HPM/TSMCHOME/sram/Compiler/tsdn28hpma2048x36m8mwsoy_110a/LEF/tsdn28hpma2048x36m8mwsoy_110a_4m.lef"
  #  lappend EDI_SLOWLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.ideal.ss_0p9v_0c_cworst.lib"
  #  lappend EDI_TYPLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.ideal.ss_0p9v_0c_cworst.lib"
  #  lappend EDI_FASTLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.ideal.ss_0p9v_0c_cworst.lib"

  #  set EDI_IDEAL_SLOWLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.ideal.ss_0p9v_0c_cworst.lib"
  #  set EDI_IDEAL_FASTLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.ideal.ff_1p05v_0c_cbest.lib"
  #  set EDI_PROP_SLOWLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.prop.ss_0p9v_0c_cworst.lib"
  #  set EDI_PROP_FASTLIB "$PHY_PATH/${MACRO_NAME}/lib/${MACRO_NAME}.prop.ff_1p05v_0c_cbest.lib"

  # lappend ATPGLIB "/process/tsmc/TSMC28HPM/TSMCHOME/digital/Front_End/mentor_dft/tcbn28hpmbwp12t35hvt_110a/tcbn28hpmbwp12t35hvt.mdt,/process/tsmc/TSMC28HPM/TSMCHOME/digital/Front_End/mentor_dft/tcbn28hpmbwp12t35_110a/tcbn28hpmbwp12t35.mdt,/projects/northport/work/anna/salvo/ET/libs/tsmc/TSMCHOME/digital/Front_End/verilog/tcbn28hpmbwp12t35lvt_101a/tcbn28hpmbwp12t35lvt.v"


## List any additional verilog libraries required for ATPG simulation 
## e.g hard macros, uncomment if required
  #    set SIM_OTHER_MODULES_LIBS  {filename1 \
  #                                 filename2 }


## Specify a manifest file which includes the list of files to be used for ATPG simulation
  #    set SIM_OTHER_MODULES_NETLISTS filelist.f
  # 


##############################################################################
## Define Design Information for Synthesis
##############################################################################

## Uncomment Set LATCHES to 1 if there are known latches in the RTL e.g if 
## clock gating exists in the RTL and not instanciating paticular technology cells
    set LATCHES 0
    
# If using threading, the MTHREAD_QUEUES env variable in setup_project must be set    
    set THREADING 0
  
# SCAN_SEQ_MODE can be 'true', 'false' or degenerated_only
# false is not default, but is recommended
    set SCAN_SEQ_MODE false

# Other attributes:    
    set BITBLAST_BUS 1
    set SET_RESET_LATCHES 0
    set UNIQUIFY_MODULES 1
    set PRESERVE_HIERARCHY 0
    set APPLET 1
    set HTML_REPORT 0
    set CLOCK_GATING 1
    set PRINT_FLOPS 0
    set PRINT_IO_CLOCKS 0
    set PRINT_SYNC_FLOPS 0  
    set TYP_85C_CORNER 0
    set RC_USE_CONFORMAL 1
    set POWER_SWITCHES 0
    set CREATE_TCASE 0	
    set REMOVE_BACKSLASH 0
    set POWER_UNIT nW
    set JLS_CLOCK 0
  #   set SWITCH_DOMAIN PD_SD_CORE 
  #   set SWITCH_PITCH 100
  #   set SWITCH_CELL HDRDID1BWP35HVT
  #   set ENABLE_NET_IN NSLEEPIN2
  #   set ENABLE_NET_OUT NSLEEPOUT2 
  
#Setting DATASHEET_PPA will override some of the setting above, and will optimise in TYP corner.
#This is to be used to provide PPA numbers for datasheets
    set DATASHEET_PPA 0    
    
## Define DEF file with floorplan for physical synthesis and EDI
  #    set FP_DEF blah/floorplan.def
  
## List modules not to be ungrouped - e.g. sync flop modules
  #    set NO_UNGROUP ""

  #set PRESERVE_INST_LIST ""
  
## List of pre mapped modules not to be touched - e.g. hierarchical synthesis
  #set PRESERVE_PRE_MAPPED_SUB_LIST ""


## Preserve List of modules - e.g. sync flop modules
  #    set PRESERVE_LIST ""

## Preserve list of nets
  #    set PRESERVE_NET ""
  
  
## Set switch for HPP MMMC files
  #    set do_synthesis 1 
##############################################################################
## Define DFT Information
##############################################################################

## Uncomment Set DEBUG_PHASE to 1 to enable automatic identification of test 
## clocks and signals. The results of this should be reviewed and during the 
## FINAL design phase, the test clocks and signals should be specified by the 
## user in the below variables
  set DEBUG_PHASE 0

## Set INSERT_SCAN to 1 to enable insertion of scan chains during synthesis
## Set INSERT_SCAN to 0 to disable scan insertion, NOTE in this case, 
## you must also set CONNECT_CHAINS to 0!
  set INSERT_SCAN 1

## Set CONNECT_CHAINS to 1 enable stitching up of scanchains
## Set CONNECT_CHAINS to 0 to disable connecting scan chains but allows 
## synthesis to map to scan flops with tie-backs if INSERT_SCAN is set to 1
## Set CONNECT_CHAINS to 0 to disable connecting scan chains if INSERT_SCAN is
## set to 0 as there will be no chains to connect!
  set CONNECT_CHAINS 1

## Variable to allow clock gates in pre-scanned blocks to be controlled without
## performing additional scan insertion
## Set RC_CLK_GATING to 1 (and both INSERT_SCAN and CONNECT_CHAINS to 0) to 
## enable control of pre-existing clock gating
  set RC_CLK_GATING 0 

## Specify existing port that is to be used as active high shift enable input
## If set to "" then a port scanen will be created
  set SHIFT_ENABLE_PORT ""

## Specify existing port that is to be used as active high test enable input 
## for RC-inserted clock gating cells.
## This can be the same port as SHIFT_ENABLE_PORT, or a different input
## If set to "" then a port scanen_cg will be created
  set TEST_CG_ENABLE_PORT ""

## Specify a list of all existing ports that are to be used as 
## active high scan mode inputs
  set TEST_MODE_PORTS {}

## Specify a list of all existing ports that are to be used as
## active low scan mode inputs
  set TEST_MODEN_PORTS {}

## Specify a list of all existing ports that are to be used as
## scan clock inputs
set TEST_CLK_PORTS {aclk rx_clk tsu_clk tx_clk pclk n_tx_clk }

## Specify a list of all existing ports that are to be used as
## active high test reset inputs
  set TEST_RST_PORTS {}

## Specify a list of all existing ports that are to be used as
## active low test reset inputs
set TEST_RSTN_PORTS {n_areset n_rxreset n_tsureset n_txreset n_preset n_ntxreset }
  
## Define the total number of scan chains to be inserted (including any pre-existing chains)
## (if NO_OF_SCAN_CHAINS is used commnet out assignment to MAX_SCAN_CHAIN_LENGTH )
  #    set NO_OF_SCAN_CHAINS 6

## Define the maximum length of the scan chains to be inserted
## (if MAX_SCAN_CHAIN_LENGTH is used comment out assignment to NO_OF_SCAN_CHAINS)
  set MAX_SCAN_CHAIN_LENGTH 200

## Specify a list of all blocks to exclude from scan insertion e.g JTAG_MACRO
  set DONT_SCAN {}

## Specify a list of all flops/instances to exclude from scan insertion
  set DONT_SCAN_INSTANCE {}

## Identify any hard macro instances inside the IP.
## Set HARD_MACRO to 1 if they include pre-existing scan, else set to 0.
  set HARD_MACRO 0
 #set MACRO_NAME <macro_cell_name>
 #set HARD_MACRO_INSTANCE_NAME {}
 
## If scan pre-exists for hard macros, and the chains are hooked up to top
## level ports in the RTL, then include these scan input ports in the following
## TCL list.  It will be assumed there are matching scan output ports.
## If only a sub-range of bits are connected to the hard macros
## (for example because other bits are reserved for hook-up during scan insertion),
## then identify the used bits using [n] or [m:n] range specifiers.
  set HARD_MACRO_SCAN_INS {}

## If there are pre-existing scan input ports in the RTL, that are to be used 
## during scan chain insertion, then include them in this TCL list.  It will be
## assumed there are matching scan output ports.  If only a sub-range of bits
## is available for use during scan insertion (for example because other bits
## are hard-wired for use with hard macros) then identify the available bits 
## using [n] or [m:n] range specifiers.  
## Note that if the number of scan chains being inserted exceeds the number 
## of available bits in this list, then additional scanin_* and scanout_* 
## ports will be created as required.
  set RTL_SCAN_INS {}

## Set BLACK_BOX to 1 if there are analog instances or known blackboxes. 
## Where possible, load an interface for all modules
  set BLACK_BOX 0

##############################################################################
## ATPG simulations corner selection (NCSIM) 
##############################################################################
## Identifies which SDF corner(s) to use for annotated ATPG simulations
## {wc} for worst case only, 
## {bc} for best case only, 
## {wc bc} for both corners, 
## or {} for no annotated simulations
    set corners {wc bc}

###################################################################
# Set the path and the basename of sdf with the variable below.
# Do not change the default settings for the soft IPs!!!
set SDFNAME ${_PNR_DATA_PATH}/$DESIGN.postccoptincr


##############################################################################
## Limit the size of files contaning the vector cycles for ATPG simulation
## The default is set to 10000
##############################################################################

set MAXVECTORS 10000

#########################################################################################
## For Hard macros only!!!!
## Change the MLM_ATPG_SIM to 1 for the simulation with MLMs
## The prerequisite is that the top-level netlist has .phys extension behind its basename
#########################################################################################
set MLM_ATPG_SIM 0


# Set the file path below if and only if the test settings for at-speed test mode 
# are different from FULLSCAN test mode and set the appropriate path, including the filename, e.g.:
# set AT_SPEED_PINASSIGNMENT_PATH <"${DUT_PATH or whatever}/DELAY/$DESIGN.pinassign for delay test">
# Otherwise, leave it as is.
set AT_SPEED_PINASSIGNMENT_FILE ""

# Specify instances of modules for which the ATPG tools cannot generate test patterns, but need 
# be isolated for test, e.g. memory blocks. Genus will automatically add bypass logic around these instances.
#set ATPG_UNTESTABLE_INSTS ""

