/***********************************************************************
 * Copyright (C) 2014-2015 Cadence Design Systems
 * All rights reserved
 ***********************************************************************
 *
 * IOCTL diagnostic command definitions for CDS-GEM reference driver
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 **********************************************************************/

#include <linux/ioctl.h>
#include <linux/sockios.h>

/* struct passed for register read or write operations */
struct emac_diag_d {
  uint32_t  addr_offs;
  uint32_t  reg_data;
};

/* Appear to need a 0x89 ID to get to a network driver - use SIOCDEVPRIVATE
 * (0x89F0) as base */

/* the IOCTL codes, generated by standard macros - rejected by network
 * device, it doesn't like the added R/W and data size fields */
/*#define CDSMAC_IOCTL_RD \
        _IOR(CDS_MAC_DIAG_IOCTL, IOCTL_DIAG_READ, struct emac_diag_d)*/
/*#define CDSMAC_IOCTL_WR \
        _IOW(CDS_MAC_DIAG_IOCTL, IOCTL_DIAG_WRITE, struct emac_diag_d)*/

#define CDSMAC_IOCTL_RD  SIOCDEVPRIVATE
#define CDSMAC_IOCTL_WR  SIOCDEVPRIVATE+1


#define CDSMAC_IOCTL_DBG_DUMP     SIOCDEVPRIVATE+5
