//------------------------------------------------------------------------------
// Copyright (c) 2003-2017 Cadence Design Systems, Inc.
//
// The information herein (Cadence IP) contains confidential and proprietary
// information of Cadence Design Systems, Inc. Cadence IP may not be modified,
// copied, reproduced, distributed, or disclosed to third parties in any manner,
// medium, or form, in whole or in part, without the prior written consent of
// Cadence Design Systems Inc. Cadence IP is for use by Cadence Design Systems,
// Inc. customers only. Cadence Design Systems, Inc. reserves the right to make
// changes to Cadence IP at any time and without notice.
//------------------------------------------------------------------------------
//
//   Filename:           tb_tx_des.v
//   Module Name:        tb_tx_des
//
//   Release Revision:   r1p12
//   Release SVN Tag:    gem_gxl_det0104_r1p12
//
//   IP Name:            GEM Gigabit Ethernet MAC
//   IP Part Number:     IP7014A
//
//   Product Type:       Off-the-shelf
//   IP Type:            Soft
//   IP Family:          Ethernet Controller
//   Technology:         N/A
//   Protocol:           Ethernet
//   Architecture:       N/A
//   Licensable IP:      SIP-Ethernet-MAC+DMA+1588+TSN+PCS+A-10M/100M/1G-IP7014A
//
//------------------------------------------------------------------------------
//   Description    :
//   This block takes serial data from the SerDes and converts it to 10 bit code
//   groups that are supplied to the PCS test bench.
//
//   The block is clocked at 1.25GHz and this is divided down by 10 to produce a
//   new 10 bit code group every 8ns. The counter does not start running until
//   a comma has been detected.
//
//------------------------------------------------------------------------------


module tb_tx_des(
                  //Interface Outputs
                    tx_parallel,
                    comdet,

                  //Interface Inputs
                    clk_1g25,
                    rst_n,
                    tx_serial_n,
                    tx_serial_p
                   );

    //Outputs
    output [9:0] tx_parallel; //Parallel output to pex
    output       comdet;      //indicates that a comma has been found
                              //used to sync the parallel data

    //Inputs
    input        clk_1g25;    //1.25GHz clock for serial rate
    input        rst_n;       //Async active low reset
    input        tx_serial_n; //Serialised input from serdes model
    input        tx_serial_p; //Serialised input from serdes model

    reg    [9:0] tx_parallel; //output parallelised data
    reg          comdet;

    reg    [9:0] tx_reg;      //internal reg used as a shifter to store
                              //parallel data prior to output
    reg    [3:0] bit_count;   //used to generate 125MHz clock synched to
                              //commas
    reg          clk125m;     //generated by counter


    //output stage
    always @(posedge clk125m or negedge rst_n)
    begin
      if (~rst_n)
        begin
          tx_parallel <= 10'b0000000000;
        end
      else
        begin
          tx_parallel <= tx_reg[9:0];
        end
    end


    //shift reg
    always @(posedge clk_1g25 or negedge rst_n)
    begin
      if (~rst_n)
        begin
          tx_reg <= 10'b0000000000;
        end
      else
        begin
          tx_reg <= {tx_serial_p,tx_reg[9:1]};
        end
    end


    //comma detect
    always @(tx_reg)
      begin
        if ((tx_reg[8:2] == 7'b1111100) | (tx_reg[8:2] == 7'b0000011))
          begin
            comdet = 1'b1;
          end
        else
          begin
            comdet = 1'b0;
          end
      end


    //counter - reset on comma detection
    always @(posedge clk_1g25 or posedge comdet)
      begin
        if (comdet)
          begin
            bit_count <= 4'b0000;
            clk125m <= 1'b0;
          end
        else
        begin
          if (bit_count == 4'b0000)
            clk125m <= 1'b1;
          else
            clk125m <= 1'b0;
          if ((bit_count == 4'b1001) )
            bit_count <= 4'b0000;
          else
            bit_count <= bit_count + 1;
        end
      end


endmodule
